services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_savings}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8060}:${PORT_WEB_UI-8060}"


volumes:
  my-datavolume: